application:
  version: @project.version@
  description: @project.description@

---
spring:
  profiles: staging
  data:
    mongodb:
      uri: mongodb://heroku_2wfkp8fj:ur54hhiar42eqh95uj3a63n6e@ds245218.mlab.com:45218/heroku_2wfkp8fj

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/articles
